spring.application.name=backend
server.port=8081
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/todolist_db
spring.datasource.username=postgres
spring.datasource.password=lolo46
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security
jwt.secret=clave_secreta_muy_segura_para_jwt_123456789
jwt.expiration=86400000

# Cors
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true